version: "2"

services:
  jenkins:
    image: jenkins
    build:
      context: docker/jenkins/
    networks:
      - metricsnet
    ports:
      - "8080:8080"
    volumes:
      - jenkins_volume:/var/jenkins_home

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - metricsnet
    environment:
      - SONAR_SCANNER_OPTS="-Xmx1024m"
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_volume:/opt/sonarqube

  db:
    image: postgres
    networks:
      - metricsnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
      - ./config/elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - metricsnet
  elasticsearch2:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
      container_name: elasticsearch2
      environment:
        - cluster.name=elasticsearch
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        - "discovery.zen.ping.unicast.hosts=elasticsearch"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - elastic_node_volume:/usr/share/elasticsearch/data
        - ./config/elasticsearch-node.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      networks:
        - metricsnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    ports:
      - 5601:5601
    networks: 
      - metricsnet
    depends_on: 
      - elasticsearch

networks:
  metricsnet:
    driver: bridge

volumes:
  sonarqube_volume:
  jenkins_volume:
  postgresql_volume:
  elastic_volume:
  elastic_node_volume: